<?php

/**
 * @file
 * Advanced aggregation validation module.
 */

/**
 * Implement hook_menu().
 */
function advagg_validator_menu() {
  $items = array();
  $file_path = drupal_get_path('module', 'advagg_validator');
  $config_path = advagg_admin_config_root_path();

  $items[$config_path . '/advagg/validator'] = array(
    'title' => 'Validator',
    'description' => 'Validate CSS/JS syntax.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('advagg_validator_admin_settings_form'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'file path' => $file_path,
    'file' => 'advagg_validator.admin.inc',
    'weight' => 10,
  );

  return $items;
}
