<?php

/**
 * Implements hook_node_insert
 */
function ildeposito_purge_node_insert($node) {
	ildeposito_purge_clear_cache($node);
}

/**
 * Implements hook_node_insert
 */
function ildeposito_purge_node_update($node) {
	ildeposito_purge_clear_cache($node);
}

/**
 * Implements hook_node_insert
 */
function ildeposito_purge_node_delete($node) {
	ildeposito_purge_clear_cache($node);
}

/**
 * Pulisce la cache in base al nodo
 * @param type $node
 */
function ildeposito_purge_clear_cache($node) {
	$varnish_host = _varnish_get_host();
	switch ($node->type) {
		case 'canto':
			$path = 'archivio/canti';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			varnish_purge($varnish_host, '^/' . $path);
			break;

		case 'traduzione':
			$path = 'archivio/traduzioni';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			varnish_purge($varnish_host, '^/' . $path);
			break;

		case 'autore':
			$path = 'archivio/autori';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			varnish_purge($varnish_host, '^/' . $path);
			break;

		case 'voce_libreria':
			$path = 'archivio/librera/mediateca';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			
			$path = 'archivio/librera/discoteca';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			
			$path = 'archivio/librera/sitoteca';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');

			break;

		case 'evento':
			$path = 'archivio/storiacantata/elenco';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			varnish_purge($varnish_host, '^/' . $path);

			$path = 'archivio/storiacantata/mappa';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			varnish_purge($varnish_host, '^/' . $path);

			$path = 'archivio/storiacantata/calendario';
			varnish_purge($varnish_host, '^/' . $path . '/.+$');
			varnish_purge($varnish_host, '^/' . $path);
			break;

		case 'articolo':
			$path = 'blog';
			varnish_purge($varnish_host, '^/' . $path . '[^/].+$');
			varnish_purge($varnish_host, '^/' . $path);
			break;
	}
}
