<?php

/**
 * Implements hook_cron.
 */
function ildeposito_news_cron() {
	$contents = ildeposito_news_check_content();
	if ($contents) {
		$newsletter = ildeposito_news_create_node($contents);
		$test_addresses = array('sergio.durzu@gmail.com');
		module_load_include('inc','simplenews','includes/simplenews.mail');
		
		/* METTE LA NEWSLETTER IN CODA */
		//simplenews_add_node_to_spool($newsletter);
	}
}

/**
 * Verifica la presenza di contenuti per il mese corrente
 * @param type $type
 * @return boolean
 */
function ildeposito_news_check_content() {
	$canti = ildeposito_news_get_contents('canti');
	$eventi = ildeposito_news_get_contents('eventi');
	$articoli = ildeposito_news_get_contents('articoli');

	if ($canti || $eventi || $articoli) {
		$contents = array(
				'Articoli' => strip_tags($articoli),
				'Canti' => strip_tags($canti),
				'Eventi' => strip_tags($eventi),
		);
		return $contents;
	} else {
		return FALSE;
	}
}

/**
 * 
 * @param type $type
 * @return boolean
 */
function ildeposito_news_get_contents($type) {
	$view = views_get_view('newsletter_utils');
	$view->set_display($type);
	$view->pre_execute();
	$view->execute();

	if (count($view->result) > 0) {
		return $view->render();
	} else {
		return FALSE;
	}
}

function ildeposito_news_create_node($contents) {
	setlocale('LC_TIME', 'ita', 'it_IT');
  $mese = strftime('%B');
	$body =  'Salve,
ecco la newsletter mensile de ilDeposito.org.
Il modo più semplice per rimanere aggiornato sulle attività e gli sviluppi del nostro archivio.
	
';	
	
	foreach ($contents as $key => $value) {
		if ($value) {
			if ($key == 'Eventi') {
				$body .= strtoupper($key . ' del mese di ' . $mese) . 
								''
								. 
								$value;
			}
			else {
				$body .= strtoupper($key . ' inseriti nel mese precedente') . 
									'
								  ' .
								$value;
			}
		}
	}
	
	$body .= 'Per avere maggiori aggiornamenti e altri segnalazioni vi invitiamo a seguirci tramite i nostri account nei social network:
		
Facebook: http://www.facebook.com/ildeposito.org
Twitter: http://twitter.com/ildeposito
GooglePlus: https://plus.google.com/u/0/+IldepositoOrgPlus/';
	

	$node = new StdClass();
	$node->type = 'simplenews';
	$node->language = LANGUAGE_NONE;
	node_object_prepare($node);
	$node->title = 'Newsletter del mese di ' . $mese;
	$node->body[LANGUAGE_NONE][0]['value'] = $body;
	$node->field_simplenews_term['it'][0]['tid'] = '293';					
	node_save($node);
	return $node;
}
