<?php

/**
 * @file
 * Gestione stampa per ilDeposito.org
 */

/**
 * Implements hook_menu
 * @return array
 */
function stampa_menu() {
	$items['stampa/canto/%'] = array(
			'page callback' => 'stampa_canto',
			'page arguments' => array(2),
			'type' => MENU_CALLBACK,
			'access arguments' => array('access content'),
	);
	return $items;
}

/**
 * Stampa PDF cantno
 * @param type $node
 */
function stampa_canto($nid) {
	$node = node_load($nid);
	if ($node && $node->type == 'canto') {
		$canto = stampa_get_canto($node);
	}

	require DRUPAL_ROOT . '/sites/all/libraries/mpdf/mpdf.php';

	$mpdf = new mPDF('it-IT', 'A4', 9, 'dejavusans');
	$stylesheet = file_get_contents(token_replace('[site:url]') . '/sites/all/modules/developer/modules/stampa/stampa.css');
	$mpdf->WriteHTML($stylesheet, 1);	
	$mpdf->SetTitle($canto['titolo'] . ' - ilDeposito.org');

	/* Intestazione e footer */	
	$mpdf->SetHeader('|ilDeposito.org - Canti di protesta politica e sociale |');
	$mpdf->SetFooter('|pagina {PAGENO}|');
	
	/* titolo */
	$mpdf->WriteHTML('<h2 class="center canto-titolo">' . $canto['titolo'] . '</h2>');

	/* contenuto */
  $mpdf->WriteHTML('<div class="small">', 2, true, false);
	$mpdf->WriteHTML('<div class="center">', 2, true, false);
	if ($canto['autori_testo']) {
		$mpdf->WriteHTML('di ' . $canto['autori_testo'] . ' ', 2, false, false);
	}

	if ($canto['anno']) {
		$mpdf->WriteHTML(' (' . $canto['anno'] . ')', 2, false, false);
	}
	$mpdf->WriteHTML('</div>', 2, false, true);

	$mpdf->WriteHTML('<div class="center">Sezione: ' . $canto['sezione'] . '</div>', 2);

	$mpdf->WriteHTML('<div class="center margin-bottom">Lingua: ' . $canto['lingua'] . ' ', 2, true, false);

	if ($canto['tags']) {
		$mpdf->WriteHTML(' - Tags: ' . $canto['tags'], 2, false, false);
	}
	$mpdf->WriteHTML('</div>', 2, false, true);
	$mpdf->WriteHTML('</div>', 2, false, true);
	$mpdf->SetColumns(2, 'J');
	$mpdf->WriteHTML('<div class="testo"><pre>' . $canto['testo'] . '</pre></div>');
	$mpdf->SetColumns(1);
	if ($canto['info'] != '[node:field-informazioni:value]') {
		$mpdf->WriteHTML('<h3 class="info">Informazioni</h2>');
		$mpdf->WriteHTML($canto['info']);
	}

	$mpdf->Output();
	exit;
}

/**
 * Recupera le infor
 * @param type $canto
 */
function stampa_get_canto($node) {
	$canto['titolo'] = $node->title;
	if (isset($node->field_accordi['und'][0]['value']) && $node->field_accordi['und'][0]['value'] != '') {
		$canto['testo'] = $node->field_accordi['und'][0]['value'];
	} else {
		$canto['testo'] = $node->field_testo['und'][0]['value'];
	}
	$canto['autori_testo'] = token_replace('[node:field-autore-testo]', array('node' => $node));
	$canto['autori_musica'] = token_replace('[node:field-autore-musica]', array('node' => $node));
	$canto['sezione'] = token_replace('[node:field-sezione]', array('node' => $node));
	$canto['tags'] = token_replace('[node:field-tags]', array('node' => $node));
	$canto['anno'] = token_replace('[node:field-anno:solo_anno]', array('node' => $node));
	$canto['lingua'] = token_replace('[node:field-lingua]', array('node' => $node));
	$canto['info'] = token_replace('[node:field-informazioni:value]', array('node' => $node));

	return $canto;
}
