<?php
/**
 * @file
 * @author  Tom McCracken <tomm@levelten.net>
 * @version 1.0
 * @copyright 2013 LevelTen Ventures
 * 
 * @section LICENSE
 * All rights reserved. Do not use without permission.
 * 
 */
namespace LevelTen\Intel;
require_once 'class.report_view.php';
require_once __DIR__ . '/../charts/class.table_chart.php';
require_once __DIR__ . '/../charts/class.pie_chart.php';
require_once __DIR__ . '/../charts/class.bubble_chart.php';

class LandingpageReportView extends ReportView {
  private $tableRowCount = 10;
  
  function __construct() {
    parent::__construct();
  }
  
  function setTableRowCount($rowCount) {
    $this->tableRowCount = $rowCount;
  }
  
  function renderReport() {
    $output = '';
    $data = $this->data;
    $startDate = $this->dateRange['start'];
    $endDate = $this->dateRange['end'];
    $reportModes = $this->modes;
    $targets = $this->targets;
    $indexBy = $this->params['indexBy'];
    $indexByLabel = $this->params['indexByLabel'];
  
    $table = new TableChart();
    $table->addColumn('string', 'Landing page');
    $table->addColumn('number', 'Views');
    $table->addColumn('number', 'Submissions');
    $table->addColumn('number', 'Sub. rate');
    $table->setOption('sortColumn', 1);
  
    foreach($data['landingpage'] AS $n => $d) {
      if (empty($d['i']) || (substr($d['i'], 0 , 1) == '_')) { continue; } 
      
      $url = $d['i'];
      $a = explode('//', $d['url']);
      if (count($a) == 2) {
        $url = 'http://' . $url;
      }
      $itemLabel = $this->formatRowString($d['title'], 60);
      $itemLink = render::link($itemLabel, $url);

      $table->newWorkingRow();
      $table->addRowItem($itemLink);
      
      $views = !empty($d['events']['Landing page view']) ? $d['events']['Landing page view']['uniqueEvents'] : 0;
      $submissions = !empty($d['events']['Landing page conversion!']) ? $d['events']['Landing page conversion!']['uniqueEvents'] : 0;
      
      $table->addRowItem($views);
      $table->addRowItem($submissions);
      $table->addRowItem(round (100 * $submissions / $views, 1));
      
      $table->addRow();

      if ($table->curRowCount >= $this->tableRowCount) {
        break;
      }
    }
    $output = '';
    
    $output .= '<div id="content-section" class="report-section">';
    $output .= '<h3>' . t('Conversions') . '</h3>';
    //$output .= $out_table; 
    $output .= $table->renderOutput();
    $output .= '</div>';

    $output .= 'generated by <a href="http://levelten.net" target="_blank">LevelTen Intelligence</a>';
    
    return '<div id="intel-report">' . $output . '</div>';
  }
}